name: Release Gravitee Resource
on:
  release:
    types: [published]

jobs:
  build:
    name: Build Gravitee Plugin
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run clean install
        run: mvn clean install
      - name: Get asset name
        run: |
          echo "FILE_NAME=$(ls target | grep .zip)" >> $GITHUB_OUTPUT
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ env.FILE_NAME }}
          asset_name: ${{ env.FILE_NAME }}
          tag: ${{ github.ref }}

